# Use lightweight official Python image
FROM python:3.9-slim

# Set working directory inside container
WORKDIR /app

# Copy the entire Backend, Pickle, and Frontend folders into container
COPY Backend ./Backend
COPY Pickle ./Pickle
COPY Frontend ./Frontend

RUN pip install --no-cache-dir fastapi uvicorn[standard] scikit-learn pandas numpy python-multipart

# Expose port 8080 for the FastAPI app
EXPOSE 8080

# Command to run the FastAPI app
CMD ["uvicorn", "Backend.app:app", "--host", "0.0.0.0", "--port", "8080"]
